// flow-typed signature: 5b0c0a2fd9ae061cfd9150e7fc1ba0a4
// flow-typed version: <<STUB>>/eslint-plugin-react-native-globals_v^0.1.2/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-native-globals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-native-globals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-plugin-react-native-globals/index' {
  declare module.exports: $Exports<'eslint-plugin-react-native-globals'>;
}
declare module 'eslint-plugin-react-native-globals/index.js' {
  declare module.exports: $Exports<'eslint-plugin-react-native-globals'>;
}
