// flow-typed signature: 14344beb69c8dbc181f5cb98c3c7f571
// flow-typed version: <<STUB>>/pigment_v^0.1.0/flow_v0.67.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pigment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pigment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pigment/basic' {
  declare module.exports: any;
}

declare module 'pigment/bin/pigment' {
  declare module.exports: any;
}

declare module 'pigment/color' {
  declare module.exports: any;
}

declare module 'pigment/core' {
  declare module.exports: any;
}

declare module 'pigment/full' {
  declare module.exports: any;
}

declare module 'pigment/models/cmyk' {
  declare module.exports: any;
}

declare module 'pigment/models/colorblind' {
  declare module.exports: any;
}

declare module 'pigment/models/hcg' {
  declare module.exports: any;
}

declare module 'pigment/models/hex' {
  declare module.exports: any;
}

declare module 'pigment/models/hsl' {
  declare module.exports: any;
}

declare module 'pigment/models/hsv' {
  declare module.exports: any;
}

declare module 'pigment/models/hwb' {
  declare module.exports: any;
}

declare module 'pigment/models/lab' {
  declare module.exports: any;
}

declare module 'pigment/models/name' {
  declare module.exports: any;
}

declare module 'pigment/models/rgb' {
  declare module.exports: any;
}

declare module 'pigment/models/schemes' {
  declare module.exports: any;
}

declare module 'pigment/models/xyz' {
  declare module.exports: any;
}

declare module 'pigment/tests/cmyk.test' {
  declare module.exports: any;
}

declare module 'pigment/tests/core.test' {
  declare module.exports: any;
}

declare module 'pigment/tests/hcg.test' {
  declare module.exports: any;
}

declare module 'pigment/tests/hex.test' {
  declare module.exports: any;
}

declare module 'pigment/tests/hsl.test' {
  declare module.exports: any;
}

declare module 'pigment/tests/hsv.test' {
  declare module.exports: any;
}

declare module 'pigment/tests/hwb.test' {
  declare module.exports: any;
}

declare module 'pigment/tests/lab.test' {
  declare module.exports: any;
}

declare module 'pigment/tests/name.test' {
  declare module.exports: any;
}

declare module 'pigment/tests/rgb.test' {
  declare module.exports: any;
}

declare module 'pigment/tests/xyz.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pigment/basic.js' {
  declare module.exports: $Exports<'pigment/basic'>;
}
declare module 'pigment/bin/pigment.js' {
  declare module.exports: $Exports<'pigment/bin/pigment'>;
}
declare module 'pigment/color.js' {
  declare module.exports: $Exports<'pigment/color'>;
}
declare module 'pigment/core.js' {
  declare module.exports: $Exports<'pigment/core'>;
}
declare module 'pigment/full.js' {
  declare module.exports: $Exports<'pigment/full'>;
}
declare module 'pigment/models/cmyk.js' {
  declare module.exports: $Exports<'pigment/models/cmyk'>;
}
declare module 'pigment/models/colorblind.js' {
  declare module.exports: $Exports<'pigment/models/colorblind'>;
}
declare module 'pigment/models/hcg.js' {
  declare module.exports: $Exports<'pigment/models/hcg'>;
}
declare module 'pigment/models/hex.js' {
  declare module.exports: $Exports<'pigment/models/hex'>;
}
declare module 'pigment/models/hsl.js' {
  declare module.exports: $Exports<'pigment/models/hsl'>;
}
declare module 'pigment/models/hsv.js' {
  declare module.exports: $Exports<'pigment/models/hsv'>;
}
declare module 'pigment/models/hwb.js' {
  declare module.exports: $Exports<'pigment/models/hwb'>;
}
declare module 'pigment/models/lab.js' {
  declare module.exports: $Exports<'pigment/models/lab'>;
}
declare module 'pigment/models/name.js' {
  declare module.exports: $Exports<'pigment/models/name'>;
}
declare module 'pigment/models/rgb.js' {
  declare module.exports: $Exports<'pigment/models/rgb'>;
}
declare module 'pigment/models/schemes.js' {
  declare module.exports: $Exports<'pigment/models/schemes'>;
}
declare module 'pigment/models/xyz.js' {
  declare module.exports: $Exports<'pigment/models/xyz'>;
}
declare module 'pigment/tests/cmyk.test.js' {
  declare module.exports: $Exports<'pigment/tests/cmyk.test'>;
}
declare module 'pigment/tests/core.test.js' {
  declare module.exports: $Exports<'pigment/tests/core.test'>;
}
declare module 'pigment/tests/hcg.test.js' {
  declare module.exports: $Exports<'pigment/tests/hcg.test'>;
}
declare module 'pigment/tests/hex.test.js' {
  declare module.exports: $Exports<'pigment/tests/hex.test'>;
}
declare module 'pigment/tests/hsl.test.js' {
  declare module.exports: $Exports<'pigment/tests/hsl.test'>;
}
declare module 'pigment/tests/hsv.test.js' {
  declare module.exports: $Exports<'pigment/tests/hsv.test'>;
}
declare module 'pigment/tests/hwb.test.js' {
  declare module.exports: $Exports<'pigment/tests/hwb.test'>;
}
declare module 'pigment/tests/lab.test.js' {
  declare module.exports: $Exports<'pigment/tests/lab.test'>;
}
declare module 'pigment/tests/name.test.js' {
  declare module.exports: $Exports<'pigment/tests/name.test'>;
}
declare module 'pigment/tests/rgb.test.js' {
  declare module.exports: $Exports<'pigment/tests/rgb.test'>;
}
declare module 'pigment/tests/xyz.test.js' {
  declare module.exports: $Exports<'pigment/tests/xyz.test'>;
}
