/* @flow */

export const LOAD_SAVED_DATA_REQUEST = 'LOAD_SAVED_DATA_REQUEST';
export const LOAD_SAVED_DATA = 'LOAD_SAVED_DATA';
export const LOAD_SAVED_DATA_FAILED = 'LOAD_SAVED_DATA_FAILED';

export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_FAILED = 'SAVE_DATA_FAILED';

export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';

export const SHOW_ADD_PALETTE = 'SHOW_ADD_PALETTE';
export const SHOW_ADD_COLOR = 'SHOW_ADD_COLOR';

export const ADD_PALETTE_FAILED = 'ADD_PALETTE_FAILED';
export const ADD_COLOR_FAILED = 'ADD_COLOR_FAILED';

export const ADD_PALETTE = 'ADD_PALETTE';
export const ADD_COLOR = 'ADD_COLOR';

export const EDIT_PALETTE = 'ADD_PALETTE';
export const EDIT_COLOR = 'ADD_COLOR';

export const DELETE_PALETTE = 'DELETE_PALETTE';
export const DELETE_COLOR = 'DELETE_COLOR';
